version: '3'


networks:
  internal:

services:
  mongo:
    networks:
      - internal
    image: 'mongo:4.4.6'
    container_name: 'mongo-card-service'
    ports:
      - '27018:27018'
  cakes-store-cart-services:
    ports:
      - '8002:8002'
    build: .
    volumes:
      - ./:/app
    networks:
      - internal

