version: '3'


networks:
  internal:

services:
  postgres:
    container_name: 'postgres-cakes'
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'qwerty'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
    ports:
      - '5432:5432'
    networks:
      - internal

  cakes-store:
    ports:
      - '8001:8001'
    build: .
    env_file:
      - ./.env
    networks:
      - internal
    depends_on:
      - postgres

