version: '3'

networks:
  internal:

services:
#    postgres:
#      container_name: 'postgres'
#      image: postgres
#      environment:
#        POSTGRES_PASSWORD: 'qwerty'
#        POSTGRES_USER: 'postgres'
#        POSTGRES_DB: 'postgres'
#      ports:
#        - '5432:5432'
#      networks:
#        - internal
    mongo:
      networks:
        - internal
      image: 'mongo:4.4.6'
      container_name: 'mongo'
      ports:
        - '27017:27017'
    cakes-store-catalog-service:
      ports:
        - '8080:8080'
      build : .
      env_file:
        - ./.env
      networks:
        - internal
